Traceback (most recent call last):
  File "lj_liquid_self_defined.gala", line 33, in <module>
    app.run(1000)
  File "/home/ylzhu/la-test/source/gamst/application.py", line 98, in run
    fi.compute(ts)
  File "/home/ylzhu/la-test/source/gamst/force.py", line 55, in compute
    self.data.calculate(timestep)
  File "/home/ylzhu/la-test/source/gamst/forces/pair.py", line 124, in calculate
    self.nlist.calculate(timestep)
  File "/home/ylzhu/la-test/source/gamst/plist.py", line 46, in calculate
    self.data.calculate(False)	
  File "/home/ylzhu/la-test/source/gamst/plists/nlist.py", line 300, in calculate
    self.clist.calculate()
  File "/home/ylzhu/la-test/source/gamst/plists/clist.py", line 149, in calculate
    self.situation = self.d_situation.copy_to_host()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 224, in _require_cuda_context
    return fn(*args, **kws)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/devicearray.py", line 264, in copy_to_host
    _driver.device_to_host(hostary, self, self.alloc_size, stream=stream)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 2245, in device_to_host
    fn(host_pointer(dst), device_pointer(src), size, *varargs)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemcpyDtoH results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFreeHost results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1708, in deref
    mem.free()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1556, in free
    self._finalizer()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1224, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 624, in _exitfunc
    f()
  File "/home/ylzhu/python/lib/python3.7/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1303, in core
    dealloc.add_item(module_unload, handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 941, in add_item
    self.clear()
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 952, in clear
    dtor(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1301, in module_unload
    driver.cuModuleUnload(handle)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/ylzhu/python/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR
